keys:
  - &admin_seirl age1c6rxcnfxn3mga8xsq86zszeskuf04wjfdvsj40qnkujwr9uy75eq8t7yyp
  - &machine_dalaran age1kpjywwdttf34xwsuxnfh88qe0e3hjfrgc796ra9faq7gdzj3ypeq04ax74
  - &machine_hyjal age1rw8ytzzha6q7fjac9szv572u8fc2589e25w5x8cata4dksan5p7q2g4q4m
  - &machine_redridge age1lwz2vr0gcjkpa4au60fjllu8zusc60aqsvp3rqy0req2597gtsdsurp0s9

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_seirl
        - *machine_hyjal
        - *machine_redridge

  - path_regex: secrets/machines/dalaran/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_seirl
        - *machine_dalaran

  - path_regex: secrets/machines/hyjal/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_seirl
        - *machine_hyjal

  - path_regex: secrets/machines/redridge/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_seirl
        - *machine_redridge
