{
  imports = [
    ./badeconomics.nix
    ./crowdbar.nix
    ./ecryptfs.nix
    ./epiquote.nix
    ./gaming.nix
    ./graphical.nix
    ./irc-client.nix
    ./laptop.nix
    ./monitoring.nix
    ./nginx.nix
    ./nvidia.nix
    ./samba_server.nix
    ./seedbox.nix
    ./smartd.nix
    ./vpn-peer.nix
    ./webuser.nix
  ];
}
