#!/usr/bin/env bash

sudo apt install \
    autossh \
    eog \
    evince \
    feh \
    gimp \
    git \
    neovim \
    nix \
    python3-venv \
    roadwarrior \
    wireguard-tools \
    wofi \


sudo tee /etc/nix/nix.conf <<EOF
sandbox = true
experimental-features = nix-command flakes
EOF
sudo usermod -a -G nix-users $USER

sudo biosmgr set \
    FnCtrlKeySwap Disable \
    FnKeyAsPrimary Enable \
