seedbox:
    transmission-htpasswd: ENC[AES256_GCM,data:sQ+tHKcnKO3BiaPRZBd7KyG1vwkm9bJiqK0EUKsjeRNdOxQsuBoH1t+SdMs=,iv:XMLu39RmoPqk3fgQnH8JPGB0w2In0ppYpEbVPR0IWoo=,tag:pCkUCDZBn3GvLubkX62hSQ==,type:str]
    downloads-htpasswd: ENC[AES256_GCM,data:lo17dFjY9rrqXydnxbukKoWDv1B4wSSiqgmLMOoEWe1lR9y25fUgCpI9BGlC4bJvwa+xa7z0Nh6oeRY+aiptNBPpaFm9EPQHLLtf+2ZMZABR7Uc1lw==,iv:usvbuEHWH511uowb/nd8M5o8QrnvL4x/0gNpMy00VPQ=,tag:d7vLktzBR0+Blc1X3Za6Iw==,type:str]
reddit-econ:
    ri-notify-bot: ENC[AES256_GCM,data:QombaSWS1xWOvNcAABVQt5Yj+/L2DXmjwXrE6TuxGH8r13zMb3zygCyO8e0jzbKYYnNRMCfWC+Pho1f0O3E5nY4ZMk6K9R4g0Jpa/7LCfKpKxi+Ddt7FoZEaaaillWkvnpjcved9hoI65dH5ffGqRW/R2eXtOI8fZgBCaMtB3wUZwNLCvlUivlNABKAZpl7VXvdBCiwW97E1fxbjCaNFy7c9t7Ta/y7Mc7QKCnrZ2ewL3bP6S/p3iZMp+QIjHHNMLzcOMGWsElAcuFBcpZ2e77HJT5ZhFbSLyh370KvEoDEqisEJJ5GNOWLOq9oP7k3L6Jm2oF2JGbBhNkEy+dIuExKBorkvZRc647b3yjOv2snaT8lOmL98Qy7hvjQCT5Wk1mGPFMZP1fS4xphZ2mclnuKoen5ryjTakke/0O1u8wq0kCPcvOuXip7dWA==,iv:5oSH9P27yJq3uZYIT3jSHkFx2tJ2/EtDDXFqmX5VoZs=,tag:C3TniawZrO+JWocLhFdZhA==,type:str]
epiquote:
    creds: ENC[AES256_GCM,data:7h4h5cEVlYCvVp7LqZQwzUvfui4ZCoeAwnawysJEg2MMx6IQvhfV9CMEiWtwcUsLaTXsOIRecO+2pasN6JUDckVQCIThxq9XCjjYi8h9rDa4H9ualh24m5f+7NKwt5pm7ZB/QcRgTIs4rD7L0Db3vhK3sdlgoKAtZFBi5aO57Jc+WukwvCWx9GGqOPJlUfj6FeI9VLbXLaoM3iGJ4bLEaKtW2KAvGp2KUFWcZ17IOy2GWgrq,iv:ENlnypUim9eFM0W3VVlY4OnpQZvO5facIK9dFCzD07s=,tag:nhensN+vZxYcL31Ef0aYqw==,type:str]
grafana:
    secret_key: ENC[AES256_GCM,data:gEg5Go0GeBemqcu4M62XCZT0pv+IYtg5,iv:cbeO8qWAUMDAFRP3U1On141+7CDeNCQn/4zovVFDjdE=,tag:j3twnAosQCNz1/PG7dWHiQ==,type:str]
    admin_password: ENC[AES256_GCM,data:FFLhQx34xbk+NWkUwjt74N498bPjWOGb,iv:BGBBpRic3jpkdOPMB7ipEOFGZTQ1HbXLb111deEWR8k=,tag:vgnxox6LorI2YqN3gJBrSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c6rxcnfxn3mga8xsq86zszeskuf04wjfdvsj40qnkujwr9uy75eq8t7yyp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUFRGSFVIQ2RJdkhWRk9l
            MkJISjRIaXZoNTJtZThZdnptNncydXkveGo4Ck9JMlNqV0lLdGtST1d2QWhNc0I5
            MDFSK3JMSnpPbTdDcWlXTU80MWdwY1kKLS0tIDdNcmNlNXNvWXlMVmMyOHdlZkxQ
            QW56QVM1Zml3N3ZBckNiYU1JclFCNHMKnif+j8YSYiyToScgXCJ+VYu5fJfn1eJh
            1bXnr59C1SkG0dS3tya3AOa+LN6O56OEeyl/kprgQ6Vg+vvift/6bg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rw8ytzzha6q7fjac9szv572u8fc2589e25w5x8cata4dksan5p7q2g4q4m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eE5oUEIxYXkxUTViM2l5
            V0wrcE9WbUc5YWI3eTdIaW9NdXVyOWJYdkIwCnB5WDNTSU5mWW1QMThicngvUXFq
            YnpKSVVVL1M2R2dBcjJSaElMYWEyOXMKLS0tIE9veXJ1RitGTWZPb2piVVk0U2U3
            b2phSEdqaTlRYndBcDB3ajdFMzNtbWMKvqxYdRDfvu199Myyy+QLnt9HU29UE2FS
            n2kf7+hqIqs+0/A1I/mrN9SArLSBcL7RE/uaicoqAIDFVjrPykaU7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lwz2vr0gcjkpa4au60fjllu8zusc60aqsvp3rqy0req2597gtsdsurp0s9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVHpUNlpMK3NRTG1WZmtz
            YUJCRTFKdndMandhNTBMdTdvNTNrdUhvckZjCjVQa0tuNktSZk5NclVsNnNhREtJ
            dk5pV1JKZnhLVkJMVk9sRlFJaUp6dWcKLS0tIFlFbmlHdVlqMGYrbG5xZmJJYnlP
            bnJaUURFL3FPQmx2bENBNzFMUm40dGcK1hc6KqgX4OP5Vu8QwJHn9w/T4Cw9vlDP
            uwL3pJxRjzCBaoP9E7y9Jf50OINQwRggbq28uWHq6rPjarCq9k/teg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T22:42:50Z"
    mac: ENC[AES256_GCM,data:A4ecb8IEbcdJu7LdjDZfm/XEVLqfXvQKham9Hm3DUYbTHGFxFrHjFnGVxjjRVfrBGRY20FhK9ziHaQ4MlvRjiU1iZC8XtKU1qHJQn8LrAWTmVuTgXCKIVlbgO5+q6UKciJrGy/WIeKAt1956Vs37j028CkfE8huZuS89fuSrpUM=,iv:fdmXPtT3eaNsfFQXe60bolvc0bxbfXUwrFJZJ5TN4VM=,tag:1wNVWH+NJTk06wjPzcENFw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
