seedbox:
    transmission-htpasswd: ENC[AES256_GCM,data:sQ+tHKcnKO3BiaPRZBd7KyG1vwkm9bJiqK0EUKsjeRNdOxQsuBoH1t+SdMs=,iv:XMLu39RmoPqk3fgQnH8JPGB0w2In0ppYpEbVPR0IWoo=,tag:pCkUCDZBn3GvLubkX62hSQ==,type:str]
    downloads-htpasswd: ENC[AES256_GCM,data:lo17dFjY9rrqXydnxbukKoWDv1B4wSSiqgmLMOoEWe1lR9y25fUgCpI9BGlC4bJvwa+xa7z0Nh6oeRY+aiptNBPpaFm9EPQHLLtf+2ZMZABR7Uc1lw==,iv:usvbuEHWH511uowb/nd8M5o8QrnvL4x/0gNpMy00VPQ=,tag:d7vLktzBR0+Blc1X3Za6Iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c6rxcnfxn3mga8xsq86zszeskuf04wjfdvsj40qnkujwr9uy75eq8t7yyp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUFRGSFVIQ2RJdkhWRk9l
            MkJISjRIaXZoNTJtZThZdnptNncydXkveGo4Ck9JMlNqV0lLdGtST1d2QWhNc0I5
            MDFSK3JMSnpPbTdDcWlXTU80MWdwY1kKLS0tIDdNcmNlNXNvWXlMVmMyOHdlZkxQ
            QW56QVM1Zml3N3ZBckNiYU1JclFCNHMKnif+j8YSYiyToScgXCJ+VYu5fJfn1eJh
            1bXnr59C1SkG0dS3tya3AOa+LN6O56OEeyl/kprgQ6Vg+vvift/6bg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rw8ytzzha6q7fjac9szv572u8fc2589e25w5x8cata4dksan5p7q2g4q4m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eE5oUEIxYXkxUTViM2l5
            V0wrcE9WbUc5YWI3eTdIaW9NdXVyOWJYdkIwCnB5WDNTSU5mWW1QMThicngvUXFq
            YnpKSVVVL1M2R2dBcjJSaElMYWEyOXMKLS0tIE9veXJ1RitGTWZPb2piVVk0U2U3
            b2phSEdqaTlRYndBcDB3ajdFMzNtbWMKvqxYdRDfvu199Myyy+QLnt9HU29UE2FS
            n2kf7+hqIqs+0/A1I/mrN9SArLSBcL7RE/uaicoqAIDFVjrPykaU7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lwz2vr0gcjkpa4au60fjllu8zusc60aqsvp3rqy0req2597gtsdsurp0s9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVHpUNlpMK3NRTG1WZmtz
            YUJCRTFKdndMandhNTBMdTdvNTNrdUhvckZjCjVQa0tuNktSZk5NclVsNnNhREtJ
            dk5pV1JKZnhLVkJMVk9sRlFJaUp6dWcKLS0tIFlFbmlHdVlqMGYrbG5xZmJJYnlP
            bnJaUURFL3FPQmx2bENBNzFMUm40dGcK1hc6KqgX4OP5Vu8QwJHn9w/T4Cw9vlDP
            uwL3pJxRjzCBaoP9E7y9Jf50OINQwRggbq28uWHq6rPjarCq9k/teg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T16:24:29Z"
    mac: ENC[AES256_GCM,data:N9XvjLSER5EdqSyWtMSaBpUXk74Jtb8xfrhrbfRd/8D2aXY6kOK43GsTnV5VUxT6oKGY9Y13MQooBJJ+dyB36r/u80HpKPT++z/Xz8qwLNavzfL26cLGj0GyysSVjTIZnoapcSNG4A2EMpsBt0wozmp4MfiU6bJ/AIzkFV4PUYE=,iv:yB3DVAsod4RiliLqV7Yj6n2/1sHWRikeKpM6kD2fXrQ=,tag:uElQRPFBN+XEip117R+TeA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
